<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Обработка-и-анализ-данных-в-Numpy-массивах" data-toc-modified-id="Обработка-и-анализ-данных-в-Numpy-массивах-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Обработка и анализ данных в Numpy-массивах</a></span></li></ul></div>




# Обработка и анализ данных в Numpy-массивах

<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 1</p>

Дано: списки `a,b=[1,1,1],[3,3,3]`

Создать одномерные массивы A и B из списков а и b.

Вычислить выражение $-((B-А)*(B/2))$

In [1]:
import numpy as np

In [2]:
#1 Ваш код здесь
import numpy as np
arrA = np.array([1,1,1])
arrB = np.array([3,3,3])

print (-1*(arrB - arrA)*(arrB/2))

[-3. -3. -3.]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 2</p>

Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)), добиться расстановки кодов "шахматных фигур".

Ожидаемый результат:
```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
 ```

In [1]:
#2. Ваш код здесь

import numpy as np

chessboard = np.zeros((8,8))
chessboard[0, :] = [-4, -3, -2, -6, -5, -2, -3, -4]
chessboard[1, :] = [-1, -1, -1, -1, -1, -1, -1, -1]
chessboard[6, :] = [1, 1, 1, 1, 1, 1, 1, 1]
chessboard[7, :] = [4, 3, 2, 6, 5, 2, 3, 4]
print(chessboard)

[[-4. -3. -2. -6. -5. -2. -3. -4.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  3.  2.  6.  5.  2.  3.  4.]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 3</p>

Средствами NumPy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа

In [4]:
# 3. Ваш код здесь
import numpy as np

numbers = np.arange(2, 21, 2)
next_odd_numbers = numbers + 1
result = even_numbers * next_odd_numbers
print(result)


[  6  20  42  72 110 156 210 272 342 420]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 4</p>

Сгенерировать двумерный массив *arr* размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0. Значения округлить (с помощью `np.round()`) до четырех десятичных знаков.

In [11]:
# 4. Ваш код здесь
import numpy as np

arr = np.random.normal(0, 20, (4, 7))
arr_rounded = np.round(arr, 4)

print(arr_normalized_rounded)


[[0.7922 0.3859 0.7283 0.7783 0.0954 0.6544 0.3062]
 [0.1883 0.9173 0.0748 0.3527 0.547  0.1122 0.29  ]
 [1.     0.     0.6959 0.6459 0.3943 0.3589 0.1685]
 [0.7831 0.0866 0.3783 0.5551 0.627  0.6477 0.7109]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 5</p>

5. Имеется массив my_array
```
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
```
Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

In [12]:
# 5. Ваш код здесь

my_array = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])


fragment = my_array[1:4, 1:4]
print(fragment)


[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 6</p>

Создайте массив *my_sin*, состоящий из синусов элементов массива *my_array*.
Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до
трёх цифр после запятой.

In [13]:
# 6. Ваш код здесь

import numpy as np

my_array = np.array([0, 30, 45, 60, 90])
my_sin = np.sin(np.radians(my_array))
sum_of_sin = round(np.sum(my_sin), 3)
print(sum_of_sin)

3.073


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 7</p>

Создать матрицу из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в матрице. Определить индекс этого значения.

In [21]:
# 7. Ваш код здесь
import numpy as np
# Создание матрицы из 20 случайных целых чисел от 0 до 100
matrix = np.random.randint(0, 100, size=(4, 5))
# Получение второго сверху значения в матрице
second_highest = np.unique(matrix)[-2]
# Определение индекса этого значения
index = np.where(matrix == second_highest)
print(index)
print(second_highest)
print(matrix)

(array([3], dtype=int64), array([1], dtype=int64))
75
[[26 41 33  3  4]
 [34 56 82 41 37]
 [19 19 33 12 44]
 [53 75 61 30 53]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 8</p>

Задать два двухмерных массива *ar1* и *ar2* размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максимум (минимум, среднее) из двух значений, находящихся на аналогичной позиции в массивах *ar1*, *ar2*.

In [ ]:
# 8. Ваш код здесь

import numpy as np

ar1 = np.random.randint(0, 11, size=(4, 7))
ar2 = np.random.randint(0, 11, size=(4, 7))

max_array = np.maximum(ar1, ar2)  # Массив максимумов
min_array = np.minimum(ar1, ar2)  # Массив минимумов
mean_array = (ar1 + ar2) / 2  # Массив средних значений


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 9</p>

Имеется массив *great_array*
```
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
```
Чему равна сумма элементов массива great_array, значение которых больше 50?

In [28]:
#9 Ваш код здесь

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T

#print(great_array)

sum_ = np.sum(great_array[great_array > 50])
print(sum_)



5470.0


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 10</p>

Переведите массив *great_array* в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?

In [33]:
# 10. Ваш код здесь

great_array.flatten()
print(great_array.flatten()[150])


7.0710678118654755


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 11</p>

Получить индексы, для которых элементы массивов A и B совпадают.
```
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
```
Ожидается результат:

```
array([1, 3, 5, 7])
```

In [40]:
# 11.
import numpy as np
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
result = np.where(A == B)[0]
print(result)

[1 3 5 7]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 12</p>

Создайте три массива: массив четных чисел от 2 до 20, массив ближайших к числам первого массива бОльших нечётных чисел, массив векторного произведения первого массива на второй. Соедините все массивы в один двумерный массив, расположив исходные массивы в столбцах.

In [46]:
# 12.  Ваш код здесь
import numpy as np

# Создаем массив четных чисел от 2 до 20
array1 = np.arange(2, 21, 2)
print(array1)
# Создаем массив ближайших к числам первого массива больших нечетных чисел
array2 = np.array([x for x in range(3, 22, 2)])
print(array2)

# Создаем массив векторного произведения первого массива на второй
array3 = np.add(array1, array2)
print(array3)

# Соединяем все массивы в один двумерный массив
array4 = np.column_stack((array1, array2, array3))
print(array4)


[ 2  4  6  8 10 12 14 16 18 20]
[ 3  5  7  9 11 13 15 17 19 21]
[ 5  9 13 17 21 25 29 33 37 41]
[[ 2  3  5]
 [ 4  5  9]
 [ 6  7 13]
 [ 8  9 17]
 [10 11 21]
 [12 13 25]
 [14 15 29]
 [16 17 33]
 [18 19 37]
 [20 21 41]]
